[project]
name = "dlt_workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,workspace]>=1.22.1",
    "duckdb>=1.4.4",
    "ibis-framework>=12.0.0",
    "marimo[recommended]>=0.20.2",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = [
    "taxi-pipeline",
]
